
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/02_model-GCP.ipynb

from xview2compgcp.nb_01b import *