
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/03b_inference_pipeline.ipynb

from xview2comp.nb_03 import *

def generate_uid_polys(polys): return np.array([str(uuid4()) for _ in polys])