
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/02d_tier3_classification_samples.ipynb

from xview2comp.nb_02c import *

def combine_nodamage_unclassified(annots):
    base_level = 'no-damage/un-classified'
    df = annots.copy()
    df.damage.replace('no-damage', base_level, inplace=True)
    df.damage.replace('un-classified', base_level, inplace=True)
    return df

@property
def get_image_area(o):
    w, h = o.size
    return w * h

Image.area = get_image_area