
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/03_damage_classification.ipynb

from xview2comp.nb_02d import *

CATS = ['nun', 'minor', 'major', 'destroyed']

def get_label(annots, fname):
    annots = annots.set_index('uid')
    return annots.loc[Path(fname).stem].damage